### PR TITLE
Add button to download the Android apk

### PR DESCRIPTION
**Pull request by uo288543**
image

### CODE REVIEW

**Comment by PabloGOP** [comment]
### I'd suggest moving the button from there to the /home page only. Please find below the arguments I have come up with:

- A footer with four elements seems strange; alignment with three elements is optimal according to my aesthetics manual.
- Users may arrive at the home page and think, 'I'd rather use the mobile app than the web interface.' However, once they are logged in and playing, whether on desktop or mobile, that feature becomes useless for them.
- Styling a button in the home view allows for more creative freedom than in the footer, where the three links already maintain a uniform style.

However, it's a great idea to include the feature, and I fully encourage the team to approve the pull request once this idea has been considered by @uo288543 and the rest of the team.

**Comment by uo288245** [comment]
I fully agree with my teammate Pablo and I think it would be better to included in other place rather than in the footer I did that looks so strange with that link. Apart from that, the idea of including the link is super cool Hugo!

**Comment by and1na** [comment]
I agree with Pablo, especially regarding the second point. Once you've started playing on the web app, why switch to the phone?

**Comment by uo288543** [comment]
I agree, i will change it tomorrow :)

**Comment by uo288347** [comment]
I like the idea very much, but maybe we can add de link to the nav bar. Imagine you are playing at home but you have to go. Maybe you'd like to continue playing but you don't remember where the link is.

**Comment by uo288543** [comment]
> I like the idea very much, but maybe we can add de link to the nav bar. Imagine you are playing at home but you have to go. Maybe you'd like to continue playing but you don't remember where the link is.

i think the nav bar already has too things and it would be overloaded

**Comment by uo288543** [comment]
I've made 4 new options for the button. Choose your favorite (all are mobile adapted).

image

Hover for fab button: 
image

Hover (only this has hover):

image

**Comment by and1na** [comment]
I go for the rounded one.

**Comment by uo288245** [comment]
I really like the button in the bottom, the one that has the hover, i think that the color fits good in the screen, and maybe if we make the PLAY button to have the same width, it would be so cool.

**Comment by uo288543** [comment]
image

**Review by PBC003 — APPROVED** [review]

**Review by PabloGOP — APPROVED** [review]

**Comment by uo288543** [comment]
image

**Review by uo288245 — APPROVED** [review]

**Comment by PabloGOP** [comment]
## In Triumph: Conquering SonarCloud with Coverage
Hail, exalted deities of GitHub, I prostrate myself before thee, filled with gratitude and awe! With humble reverence, I thank thee for thy divine guidance and intervention of my mate Hugo. Through his fervent commits, he has achieved a glorious victory, attaining an 100% coverage, triumphing over the infernal specter of SonarCloud. Accept this triumph as an offering, O guardians of code, and may my repositories shine ever brighter in thy sight. Glory be to thee, now and forevermore!

**Review by uo288347 — APPROVED** [review]

**Pull request merged**
