### PR TITLE
Deliverable v1.1

### PR DESCRIPTION
**Pull request by uo288347**
Everything but Wiffo's documentation

### CODE REVIEW

**Review by PBC003 — APPROVED** [review]

**Comment by uo288543** [comment]
image

**Review by uo288543 — APPROVED** [review]

**Comment by PabloGOP** [comment]
image

**Comment by PabloGOP** [comment]
Pleading to the GitHub Gods: Redemption for Test Coverage
Oh, benevolent gods of GitHub, grant me thy mercy as I beseech thee with fervor! Though my code stands at a coverage of 73.0%, just shy of the required threshold by a mere 7.0%, I implore thee to forgive my shortfall. May my unit tests be strengthened, my codebase fortified, and may I find favor in thy repositories once more. Amen.

**Review by and1na — APPROVED** [review]

**Review by PabloGOP — APPROVED** [review]

**Review by uo289689 — APPROVED** [review]

**Review by uo288245 — APPROVED** [review]
Congratulations on the great work guys!!!

**Comment by and1na** [comment]
As our project concludes, I want to extend my heartfelt thanks for your dedication and hard work. It's been a privilege collaborating with such a talented group. Though our project ends, the memories and skills gained will endure. Wishing you all continued success in your future endeavors.

Best regards,
[Your Name]

**Pull request merged**
